version: '3.8'

services:
  fintech-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fintech-telegram-bot-prod
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      # Telegram Bot Configuration
      - BOT_TOKEN=${BOT_TOKEN}
      
      # Bot Settings
      - BOT_USERNAME=${BOT_USERNAME}
      - BOT_ADMIN_USER_IDS=${BOT_ADMIN_USER_IDS}
      - MAIN_CONTENT_CREATOR_ID=${MAIN_CONTENT_CREATOR_ID}
      
      # N8N Integration
      - BASE_N8N_WEBHOOK_URL=${BASE_N8N_WEBHOOK_URL}
      
      # Logging
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FILE=${LOG_FILE:-logs/bot.log}
      
      # Environment
      - NODE_ENV=production
      - PORT=${PORT:-3000}
      
      # Database
      - DATABASE_URL=${DATABASE_URL}
      
      # Cron Schedule
      - POSTING_SCHEDULE=${POSTING_SCHEDULE:-"0 12 */2 * *"}
      
      # Supabase Configuration
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      
      # Channels Configuration
      - CHANNELS=${CHANNELS}
    volumes:
      - ./logs:/app/logs:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      - fintech-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 2m
      timeout: 5s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"



networks:
  fintech-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
